### ISSUE TITLE
Transmitted packet corruption

### ISSUE THREAD

**Issue by brianbezanson** [UBNanosatLab/lfr-firmware#26] opened 2020-03-07 19:45 UTC
Occasionally a packet will be corrupted, with data from the beginning of the packet repeated in the middle.  Suspicions point toward transmit ring buffer.

**Comment by iracigt** [comment] 2020-06-12 21:10
Fixed in ad74cdb33059f53ed95027956446f4205c2ccad7.

Root cause was a logic error in `pkt_buf_enqueue` when wrapping around the edge of the buffer. The data copied after the wrap around was a repeat of the beginning of the packet.

**Closed by iracigt** 2020-06-12 21:10 UTC
Labels: bug
